### ISSUE TITLE
i have to add migration and column's id

### ISSUE THREAD

**Issue by jerrynim** [AnjaneyuluBatta505/gin-graphql-postgres#1]
Thank you for Sharing. your post and code.
i followed this, and i have to add migration at 'server.go'
and, i have to add question's id.

so, it works well. 🎉

**Comment by vignesh-codes** [comment]
@jerrynim  @AnjaneyuluBatta505 
Thank you for your tutorial. its nicely explained. 
I am having issues with migrating the schema to db. I can run and access the endpoint. However, it says 
'relation "questions" does not exist' 
whenever i try to perform query and mutation. 
What changes should i make to solve this?
